version: '3'
services:
  lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/pigeon-tracker
    working_dir: /pigeon-tracker
    command:
      - jupyter
      - lab
      - --allow-root
      - --ip=0.0.0.0